/* EXERCICIO LIVRARIA*/

CREATE DATABASE Livraria;

CREATE TABLE AUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME varchar(100) NOT NULL,
	NACIONALIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME varchar(100) NOT NULL,
);

CREATE TABLE CATEGORIA 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	TIPO_CATEGORIA varchar(100) NOT NULL,
);
CREATE TABLE LIVRO
(
	ISBN VARCHAR(15) NOT NULL PRIMARY KEY ,
	TITULO varchar(100) NOT NULL,
	ANO_PUBLICACAO DATETIME NOT NULL,
	FK_AUTOR INTEGER NOT NULL,
	FK_EDITORA INTEGER NOT NULL,
	FK_CATEGORIA INTEGER NOT NULL,
	FOREIGN KEY (FK_AUTOR) REFERENCES AUTOR(ID),
	FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(ID),
    FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE LIVRO_AUTOR 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_LIVRO VARCHAR(15) NOT NULL,
	FK_AUTOR INTEGER NOT NULL,
	FOREIGN KEY (FK_LIVRO) REFERENCES LIVRO(ISBN),
    FOREIGN KEY(FK_AUTOR) REFERENCES AUTOR(ID)
);

DROP TABLE LIVRO
DROP TABLE AUTOR;
DROP TABLE CATEGORIA;
DROP TABLE EDITORA;
DROP TABLE LIVRO_AUTOR;

SELECT * from LIVRO;
SELECT * FROM AUTOR; 
SELECT * FROM LIVRO_AUTOR;
SELECT * FROM CATEGORIA;
SELECT * FROM EDITORA;

INSERT INTO EDITORA VALUES ('Rocco');
INSERT INTO AUTOR VALUES ('J.K. Rowling','Inglaterra');
INSERT INTO CATEGORIA VALUES('Literatura Juvenil');
INSERT INTO LIVRO VALUES('8532511015', 'Harry Potter e a Pedra Filosofal', '2000', '1','1','1' );

INSERT INTO EDITORA VALUES ('Wmf Martins Fontes');
INSERT INTO AUTOR VALUES ('Clive Staples Lewis','Inglaterra');
INSERT INTO LIVRO VALUES('98755674564', 'As Crônicas de Nárnia', '2009', '2','2','1' );

INSERT INTO EDITORA VALUES ('Casa da Palavra');
INSERT INTO AUTOR VALUES ('Affonso Solano','Brasil');
INSERT INTO CATEGORIA VALUES('Ficção Científica');
INSERT INTO LIVRO VALUES('8923482399', 'O Espadachim de Carvão', '2013', '3','3','2' );

INSERT INTO EDITORA VALUES ('Belas Letras');
INSERT INTO AUTOR VALUES ('Marcos Piangers','Brasil');
INSERT INTO CATEGORIA VALUES('Humor');
INSERT INTO LIVRO VALUES('2349089009', 'O Papai é Top', '2015', '4','4','3' );

INSERT INTO EDITORA VALUES ('Matrix');
INSERT INTO AUTOR VALUES ('Ciro Botelho - Tiririca','Brasil');
INSERT INTO LIVRO VALUES('9897927321', 'Pior que tá não Fica', '2015', '5','5','3' );

INSERT INTO AUTOR VALUES ('Bianca Mól','Brasil');
INSERT INTO LIVRO VALUES('674844565', 'Garota Desdobrável', '2015', '5','3','1' );

INSERT INTO LIVRO VALUES('6785678645', 'Harry Potter e o Prisioneiro de Azkaban', '2000', '1','1','1' );


DELETE FROM livro;

SELECT L.ISBN, L.TITULO, L.ANO_PUBLICACAO AS ANO,E.NOME AS EDITORA, A.NOME AS AUTOR, A.NACIONALIDADE AS NACIONALIDADE, C.TIPO_CATEGORIA AS CATEGORIA
FROM LIVRO L
JOIN AUTOR A ON L.FK_AUTOR = A.ID
JOIN EDITORA E ON L.FK_EDITORA = E.ID
JOIN CATEGORIA C ON L.FK_CATEGORIA = C.ID
ORDER BY TITULO;

DELETE FROM AUTOR WHERE ID = 6;