CREATE TABLE ALUNOS 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	IDADE INTEGER
);


CREATE TABLE CURSOS

(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    CARGA_HORARIO INTEGER NOT NULL,
    ATIVO BIT DEFAULT 1,
    DESCRICAO TEXT
);

CREATE TABLE DISCIPLINAS 
(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    CARGA_HORARIA INTEGER NOT NULL,
    FK_CURSO INTEGER NOT NULL,
    FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID)
);

CREATE TABLE MATRICULAS
(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    FK_ALUNO INTEGER NOT NULL,
    FK_CURSO INTEGER NOT NULL,
    FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID),
    FOREIGN KEY(FK_CURSO) REFERENCES CURSOS(ID)
);

DROP TABLE ALUNOS;


/* EXERCICIO LIVRARIA*/

CREATE DATABASE Livraria;

CREATE TABLE AUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME varchar(100) NOT NULL,
	NACIONALIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME varchar(100) NOT NULL,
);

CREATE TABLE CATEGORIA 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	TIPO_CATEGORIA varchar(100) NOT NULL,
);
CREATE TABLE LIVRO
(
	ISBN VARCHAR(15) NOT NULL PRIMARY KEY ,
	TITULO varchar(100) NOT NULL,
	ANO_PUBLICACAO DATETIME NOT NULL,
	FK_EDITORA INTEGER NOT NULL,
	FK_CATEGORIA INTEGER NOT NULL,
	FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(ID),
    FOREIGN KEY(FK_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE LIVRO_AUTOR 
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_LIVRO VARCHAR(15) NOT NULL,
	FK_AUTOR INTEGER NOT NULL,
	FOREIGN KEY (FK_LIVRO) REFERENCES LIVRO(ISBN),
    FOREIGN KEY(FK_AUTOR) REFERENCES AUTOR(ID)
);