
CREATE DATABASE ADONET;

CREATE TABLE PESSOAS
(
ID INTEGER PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
PROFISSAO VARCHAR (30)
)

CREATE LOGIN atos WITH PASSWORD='senha123';
CREATE USER usuario FROM LOGIN atos;
EXEC sp_addrolemember 'DB_DATAREADER', 'usuario';
EXEC sp_addrolemember 'DB_DATAWRITER', 'usuario';


INSERT INTO PESSOAS VALUES ('Zé', 'Programador');

select * from PESSOAS;